name: Smoke Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: |
          sudo chmod -R 777 ${{ github.workspace }}
          sudo rm -rf ${{ github.workspace }}/.github

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Start Selenoid
        uses: n-ton4/selenoid-github-action@master
        id: start-selenoid
        continue-on-error: false
        with:
          version: 1.10.1
          args: -limit 10
          browsers: chrome
          last-versions: 1
      - name: Check Selenoid has been started
        run: curl http://localhost:4444/status

      - name: Run Selenide Tests
        run: |
          ./gradlew suiteTest -PType=suiteTest

      - name: Print Selenoid Logs
        run: docker logs $(docker ps -q --filter ancestor=aerokube/selenoid:latest-release)

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history