name: Smoke Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenoid:
        image: aerokube/selenoid:latest-release
        ports:
          - 4444:4444
        options:
          --env DOCKER_API_VERSION=1.39
          --env OVERRIDE_VIDEO_OUTPUT_DIR=/tmp/video
          --env OVERRIDE_LOG_OUTPUT_DIR=/tmp/logs
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /tmp/video:/tmp/video
          - /tmp/logs:/tmp/logs
          - ${{ github.workspace }}/.github/browserConfig/browsers.json:/etc/selenoid/browsers.json
      selenoid-ui:
        image: aerokube/selenoid-ui:latest-release
        ports:
          - 8080:8080
        options:
          --link selenoid
          --env DOCKER_API_VERSION=1.39

    steps:
      - name: Clean workspace
        run: |
            sudo chmod -R 777 ${{ github.workspace }}
            sudo rm -rf ${{ github.workspace }}/.github

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Adjust file permissions
        run: sudo chmod -R 777 .github/browserConfig/browsers.json

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Run Selenide Tests
        run: |
          ./gradlew suiteTest -PType=suiteTest

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history